# Generated by Django 4.1.1 on 2022-10-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('company', models.TextField()),
                ('color', models.TextField()),
                ('RAM', models.TextField()),
                ('memory', models.TextField()),
                ('price', models.TextField()),
                ('img_url', models.TextField()),
            ],
        ),
    ]
