# Generated by Django 4.1.1 on 2022-10-12 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
